# Generated by Django 5.1.2 on 2024-10-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furnitureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_db',
            name='pro_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
