# Generated by Django 5.1.2 on 2024-10-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_db',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
